name: Clang-Format Check

on:
  pull_request:
    branches:
      - master

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up clang-format
        run: sudo apt-get install -y clang-format

      - name: Run clang-format
        run: find . -name '*.cpp' -o -name '*.h' -o -name '*.c' -o -name '*.hpp' | xargs clang-format -i

      - name: Check for formatting changes
        run: git diff --exit-code
